// This file is generated by the Firebase CLI
// You would normally generate this using the FlutterFire CLI
// Example placeholder - your actual file will be different

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAlx65BmNjkgpLT63KFASr0SleKL4VvTA',
    appId: '1:1089242082795:android:4d504e94e36140ca817dae',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'smart-lib-41db1',
    authDomain: 'YOUR-AUTH-DOMAIN',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    measurementId: 'YOUR-MEASUREMENT-ID',
    databaseURL: 'https://smart-lib-41db1-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAlx65BmNjkgpLT63KFASr0SleKL4VvTA',
    appId: '1:1089242082795:android:4d504e94e36140ca817dae',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'smart-lib-41db1',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    databaseURL: 'https://smart-lib-41db1-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'YOUR-IOS-BUNDLE-ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: 'YOUR-APP-ID',
    messagingSenderId: 'YOUR-MESSAGING-SENDER-ID',
    projectId: 'YOUR-PROJECT-ID',
    storageBucket: 'YOUR-STORAGE-BUCKET',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'YOUR-IOS-BUNDLE-ID',
  );
}